{100}{}{你看见一个超级变种人。他看守着气闸室的门。}
{101}{}{你看见一个超级变种人卫兵。}
{102}{}{耶利米，你可以通过。}
{103}{}{往前走。}
{104}{}{快点走，传信的。}
{105}{}{普通人类不能在这里携带武器！不许动，说明你是谁！}
{106}{}{呃!}
{107}{}{嗯，对不起。我会把它收起来的。}
{108}{}{我只是通过这里。这里没有必要做什么身份证明。}
{109}{}{去死！死！死！我一直想这么说。}
{110}{}{我不会再这么说了。你要接受惩罚。}
{111}{}{不许动！你来这里有什么事，孩子？}
{112}{}{嗯!}
{113}{}{我啊，嗯, 做事。}
{114}{}{我在这里有很重要的事情要做。你没有权力阻止我或查问我。}
{115}{}{别跟我说，大家伙。}
{116}{}{你的回答不会放松我的神经。马上和明确的回答我，否则我会假定你是为了达到邪恶目的而来这里。我以为你也不会希望如此的……}
{117}{}{嗯，不，真的，没撒谎，我就是来做事的。}
{118}{}{我带来一则信息给我们的领袖。}
{119}{}{我感觉到你的言辞的虚假。我不会让你进来的。这点我可以保证……}
{120}{}{你可以通过，不过下一次，要遵循合适的程序……}
{121}{}{好，谢谢。待会儿见。}
{122}{}{又有什么事？}
{123}{}{祝福你，兄弟。}
{124}{}{一个主教的真正跟随者应该清楚这些。你是一个入侵者！}
{125}{}{往前走。我没有时间回答你的问题。}
{126}{}{你很烦人啊。}
{127}{}{我有工作要做。你呢？}
{128}{}{你出现在这里犯了大错。解释或者死……}
{129}{}{噗嗤!}
{130}{}{我没有什么好说的。}
{131}{}{我来这就是为了从你这种家伙的手里拯救人类。}
{132}{}{哦，闭嘴！}
{133}{}{你不应该用装疯卖傻来愚弄我。我对这厌倦了……}
{134}{}{这实在是愚蠢的固执态度，我们都是“人类”。我们和你们一样都是人类。}
{135}{}{这是什么垃圾？}
{136}{}{你不可能是人类。}
{137}{}{我的名字是凯尔。我也和你们一样，是父母生的。主教监督了我重生的过程。这些肌肉、这类皮肤、这种力量让我不亚于如你的任何人类。我并不喜欢融合代表的所有事物，但这却是我们获得和平的机会中的最好的办法。}
{138}{}{就我的观察，这可是错误的. 我来这里就是为了终结你和你的种族。}
{139}{}{你可能算是人类，但是这并不意味着你们的融合就是正确的。我想我们相互会是敌人。}
{140}{}{很遗憾你这么做，不过你不会再继续下去了……}
{141}{}{看到你的脑袋插在矛上实在会是一个遗憾。}
{142}{}{入侵者！}
{143}{}{我不会再和你说话了。}
{200}{}{通过蒙骗守卫获得通行，你获得}
{201}{}{点经验值。}




#{100}{}{You see a super mutant. He is guarding the airlock door.}
#{101}{}{You see a super mutant guard.}
#{102}{}{耶利米, you may pass.}
#{103}{}{Move along.}
#{104}{}{Move faster, messenger.}
#{105}{}{Normals cannot carry weapons here! Halt and identify yourself!}
#{106}{}{Grrr!}
#{107}{}{Uh, sorry. I'll put it away.}
#{108}{}{I'm just passing through. No need for identities here.}
#{109}{}{Die! Die! Die! I always wanted to say that.}
#{110}{}{I will not be spoken to that way. You will be punished.}
#{111}{}{Halt! What is your business here, 'child'.}
#{112}{}{Hng!}
#{113}{}{I'm, uh, doing stuff.}
#{114}{}{I'm on important business. You have no right to stop and question me.}
#{115}{}{Don't talk to me, big boy.}
# {116}{}{Your answer does not settle my nerves. Speak quickly and clearly, or
 # I will assume you are here for foul purposes. I assure you that you will
 # not like that...}
#{117}{}{Uh, no, really, honestly. I'm doing stuff.}
#{118}{}{I'm bringing a message to our leader.}
#{119}{}{I sense the untruth behind your words. You will not be allowed in. This I promise you...}
#{120}{}{You may pass, but next time, follow the proper procedure...}
#{121}{}{Ok, thanks. See you around.}
#{122}{}{And what's that?}
#{123}{}{Blessing to you, brother.}
#{124}{}{A true follower of the Master would have that knowledge. You are an intruder!}
#{125}{}{Move along. I don't have time for your questions.}
#{126}{}{You are annoying me.}
#{127}{}{I have work to do. Do you?}
#{128}{}{You are making a mistake by coming here. Explain yourself or perish...}
#{129}{}{Nuggie!}
#{130}{}{I have nothing to say.}
#{131}{}{I'm here to protect humanity from the likes of you.}
#{132}{}{Oh, shut up!}
#{133}{}{You should not try to fool me by playing dumb. I tire of this...}
#{134}{}{What kind of foolish bigotry is that, we are 'humanity.' We're just as human as you are.}
#{135}{}{What kind of crap is that?}
#{136}{}{There is no possible way that you are human.}
#{137}{}{My name is 凯尔. I was born to a mother and a father, like yourself.
 # The Master just oversaw my rebirth. These muscles, this skin, this strength
 # does not make me any less human than you. I do not like all that the Unity
 # stands for, but it is the best chance for peace that we have.}
#{138}{}{Not on my watch, it isn't. I'm here to put an end to you and your kind.}
#{139}{}{You may be human, but that still doesn't make your Unity right. I guess we will be enemies.}
#{140}{}{It is a pity that you act this way, but you will not proceed further...}
#{141}{}{It will be a true shame to see your head on a pike.}
#{142}{}{Intruders!}
#{143}{}{I no speak to you.}
#{200}{}{You gain }
#{201}{}{ experience points for bluffing your way past the guards.}
