{100}{}{你看见百货商店的米奇。}
{101}{}{今天我有什么能帮你吗？}
{102}{}{我想买点东西。}
{103}{}{我想卖点东西。}
{104}{}{没什么事。谢谢。}
{105}{}{溜达。}
{106}{}{好，这些东西是我所有的。}
{107}{}{很好，我总爱寻求新东西。}
{108}{}{抱歉，我听不明白。当你变聪明点再回来吧。}
{109}{}{谢谢。下次在来哦。}
{110}{}{你看见武器商杰克。}




#{100}{}{You see Mitch of the All-N-One store.}
#{101}{}{How may I help you today?}
#{102}{}{I'd like to buy something.}
#{103}{}{I'd like to sell something.}
#{104}{}{Nothing. Thanks.}
#{105}{}{Runk.}
#{106}{}{Great. Here's what I have.}
#{107}{}{Great, always looking for new things.}
#{108}{}{Sorry, I can't understand you. Come back when you get more of a brain.}
#{109}{}{Thanks. Come again.}
#{110}{}{You see Jake the Arms Dealer.}
