
#
# Talking cows special encounter text
#


#{100}{}{Moo.}
{100}{}{哞！知道吗，BN13那些汉化辐射1的汉化小组成员根本就不懂英文。}

#{101}{}{Moo!}
{101}{}{哞！在我的身体里就有一个净水芯片，但是杀了我，我也不给你。}

#{102}{}{Moo, I say.}
{102}{}{哞哞哞哞！哞~！哞~！哞哞~哞~哞！哞哞~哞~！哞哞~哞~！哞哞~哞~！哞~哞哞哞！哞~哞！哞哞~哞~哞~哞~！哞哞哞哞~哞~！哞哞~哞哞~！哞~哞~哞~！哞~哞~！没听懂？人类真是愚蠢啊，没听出来这句话是摩尔斯密码吗？就是httpwwwbn13com的意思。}

#{103}{}{It's a wild Brahmin.}
{103}{}{那是一只野生双头牛。}

#{104}{}{There is nothing natural about these cows. The second head can only be the result of some strange mutation.}
{104}{}{这些牛不是原来就这样的。第二个脑袋显然是辐射变异的结果。}

#{105}{}{Looks pretty normal to you.}
{105}{}{看起来似乎很正常。}



