
#{100}{}{Never before in your life have you seen a natural darkness like this one. It almost looks unnatural to you.}
#{101}{}{You barely manage to keep your fears in check, but you are able to move into the darkness.}
{100}{}{你看到自然造成的黑暗，这是以前在你的生命中从来没有过的。这对你来说太不正常了。}
{101}{}{你勉强控制着你的恐惧，进入黑暗之中。}