# {100}{}{You see Leone.}
# {101}{}{If you want company, rent a hooker. I'm busy.}
# {102}{}{Not until the boss says so. Just ignore him and he'll go away.}
# {103}{}{Not until the boss says so. Just ignore her and she'll go away.}
# {105}{}{Give me a break. Anyone can bust a knee of break fingers. It just don't have the shock people like is used to.}
{100}{}{你看到利昂。}
{101}{}{如果你想要个伙伴就去雇个小偷，我很忙。}
{102}{}{在老板发话之前他只能离开。}
{103}{}{在老板发话之前她只能离开。}
{105}{}{别吹了。玩过生化危机吗？我是那里的男主角。}