#{100}{}{You see a strong, stout man with a bushy beard.}
{100}{}{你看见一个满脸胡须强壮的男人。}

#{101}{}{You see MacRae.}
{101}{}{你看见麦克雷。}

#{102}{}{Hello Lad, what might you be looking for today?}
{102}{}{你好小伙子，今天你在寻找什么？}

#{103}{}{Hello Lass, what might you be looking for today?}
{103}{}{你好小姑娘，今天你在寻找什么？}

#{104}{}{Ai, What else would you be looking to know?}
{104}{}{哎，你想知道些别的什么吗？}

#{105}{}{Who are you?}
{105}{}{你是谁？}

#{106}{}{What can you tell me about the Blades?}
{106}{}{你能告诉我关于利刃帮的事吗？}

#{107}{}{Nothing, thanks.}
{107}{}{没事，谢谢。}

#{108}{}{Well, I'm MacRae.  I help the Blades some against the Deathclaws and that Regulator bunch.
#  Teach'em a bit about protectin 'emselves against those nasties.}
{108}{}{很好，我是麦克雷。我帮助利刃帮对抗死亡爪和那些管理者。教他们如何对抗那些下流胚的技能。}

#{109}{}{What kind of stuff do you teach them?}
{109}{}{你教他们什么东西？}

#{110}{}{Have you seen the Deathclaws?}
{110}{}{你有看到死亡爪吗？}

#{111}{}{What's the deal with the Regulators}
{111}{}{管理者有什么问题？}

#{112}{}{Can I ask you something else?}
{112}{}{我能问你别的吗？}

#{113}{}{Well m' specialty is fightin with my fists, and takin a punch or two more than 
#the guy throwin 'em at me.}
{113}{}{我拿手的是用拳头打架，我一拳就可以打倒一两个人。}

#{114}{}{Sounds like a dumb idea, I'd rather use a gun.}
{114}{}{听起来像是个馊主意,我宁可用枪。}

#{115}{}{Do you think you could teach me anything?}
{115}{}{您认为可以能教我什么？}

#{116}{}{Can I ask you something else?}
{116}{}{我能问你别的吗？}

#{117}{}{Well if that's how you be feeling, you can just turn yourself around and walk away.}
{117}{}{很好，如果那是你所想的，你现在可以转身离开了。}

#{118}{}{You seem to be an alright lad, but me times busy with keeping the Blades schooled.  If 
#things were to straighten themselves, I might be havin the time then.}
{118}{}{你似乎是个好青年，但是我正忙着教利刃帮。如果事情顺利了，我可能会有时间。}

#{119}{}{Alright, can I ask you something else?}
{119}{}{好吧，我能问你别的吗？}

#{120}{}{Thanx for the info.}
{120}{}{谢谢你的信息。}

#{121}{}{Seen em I have.  Ran like hell, I did.  If yer lookin for 'em, you'll find 'em over there. 
#【MacRae points over to the east】}
{121}{}{我看到过它们。如果看到它们，最好拼命地跑开。你会在那边找到它们。【麦克雷指了指东边】}

#{122}{}{I was thinkin the Deathclaws were the spawn of an unnatural act, but 'em Regulators are evil.  
#Come once a month or so and they shows their ugly faces and drag a father away from is wee ones.}
{122}{}{我认为死亡爪是非自然的产物，但是它们的管理者是邪恶的。他们差不多每月来一次，然后展现他们丑陋的脸并且阻止父亲靠近这些小家伙。}

#{123}{}{Anything I could do to help?}
{123}{}{我可以帮你做什么？}

#{124}{}{Sounds bad, could I ask you another question?}
{124}{}{听起来不好，我能问你别的问题吗？}

#{125}{}{Thanks for the info.}
{125}{}{谢谢你的信息。}

#{126}{}{You be wantin to talk to Razor.  A good lass if there ever was one.}
{126}{}{你需要去和剃刀说话。她曾经是一个好女孩。}

#{127}{}{A good group of people is what the Blades are.  Stuck ere between the damn Regulators and the 
#Deathclaws ain't meant the happiest life for em, but they survive.}
{127}{}{利刃帮是一群好人。在死亡爪和管理者之间为他们所谓的幸福生活战斗。}

#{128}{}{【MacRae claps you on the back】 Thanks to you, the Blades are going to live a better life.  So, 
#what can an old Scotsman do for ya?}
{128}{}{【麦克雷在对你鼓掌】谢谢你，利刃帮将要得到更好的生活。那么老苏格兰人能为你做些什么？}

#{129}{}{You had said earlier that if you had some free time, you could teach me a few things.}
{129}{}{你先前说过如果有了一些自由的时间，你可以教我一些东西。}

#{130}{}{What have you been doing lately?}
{130}{}{你最近做了什么？}

#{131}{}{What do you do around here?}
{131}{}{你在附近干什么？}

#{132}{}{Not a problem.}
{132}{}{没问题。}

#{133}{}{Well it's been a wee bit quiet since the Blades helped out Adytum with the Regulators.  Me 
#teaching services haven't been in such demand.}
{133}{}{自从帮助利刃帮对抗内城的管理者以后，这地区就稍微安宁了些。我的教学服务不能用在这方面上。}

#{134}{}{What do you teach?}
{134}{}{你教什么？}

#{135}{}{Sorry to hear that, hope things get more interesting?}
{135}{}{很遗憾听到那些，希望事情能有转机吗？}

#{136}{}{Could you teach me?}
{136}{}{您可以教我吗？}

#{137}{}{Sounds interesting, but I gotta get going.}
{137}{}{听起来很有趣，但是我必须要走了。}

#{138}{}{Well I guess I do have the time.  Might as well start right now. 【MacRae starts showing you some 
#fighting stances, and ways to take punches like a true Scotsman.】}
{138}{}{很好，我想我有时间。最好现在开始。【麦克雷开始摆出一些战斗架势，而且像一个真正的苏格兰人那样出拳了。】}

#{139}{}{You be a quick learner.  Hope that helps you in your travels.}
{139}{}{你学得很快。希望能在你的旅行中帮助你。}

#{140}{}{Well I used to be helpin the Blades out by teachin them a few things about protectin themselves 
#against the DeathClaws and the Regulators.  Now with you takin care of all that, things have been a wee 
#bit on the boring side lately.}
{140}{}{很好，我过去一直在教利刃帮防身的技能以帮助他们对抗死亡爪和管理者。现在由你去搞定一切，往后就会有点无聊了。}

#{141}{}{Good seein ya.}
{141}{}{很高兴见到你。}


