#{100}{}{You see Tandi.}
{100}{}{你看到坦蒂。}
#{101}{}{What else is around these parts?}
{101}{}{这附近还有别的什么吗？}
#{102}{}{What's going on around here?}
{102}{}{这附近发生了什么事？}
#{103}{}{Have you heard any stories from down south?}
{103}{}{你听说过南方的一些事吗？}
#{104}{}{How do you like it here?}
{104}{}{你喜欢这里吗？}
#{105}{}{Well, that's about it. Thanks for your time.}
{105}{}{很好，谢谢你。}
#{106}{TAND_1}{Hi!  I heard there was a traveller in town, but I was
 #kinda skeptical until I saw you.  My name's Tandi, what's yours?}
{106}{}{你好！我听说小镇里来了个旅行者，不过直到在我见到你之前我还有点不太相信。我的名字叫坦蒂，你呢？}
#{107}{}{My name is }
{107}{}{我的名字叫}
#{108}{}{.}
{108}{}{。}
#{109}{}{The name is }
{109}{}{名字是}
#{110}{}{.#Remember it.}
{110}{}{。记住了。}
#{111}{}{Uhhh?}
{111}{}{嗯？}
#{112}{tand_2}{Well..how do you like our little town?  Bored yet?}
{112}{tand_2}{好的……你觉得我们的小镇怎么样？有意思吗？}
#{113}{}{It's okay. Can I ask you a few questions, though?}
{113}{}{那好吧。我还可以问你一些问题吗？}
#{114}{}{Hell, yes. There's nothing to do here but watch the Brahma mate.}
{114}{}{该死，是的。这儿除了看双头牛交配以外就没什么好做的了。}
#{115}{}{I guess it's okay.}
{115}{}{我猜它是对的。}
#{116}{}{Well, yes. It is a bit boring.}
{116}{}{嗯，是的。就是有一点无聊。}
#{117}{TAND_3}{ Sure, I guess.  I've never been out of here, so I don't know
 #what help I can be.  So, what'cha need?}
{117}{TAND_3}{好啊，我想想。我从没有离开过这里，所以我不知道有什么可以帮忙的。那么，需要我做什么呢？}
#{118}{TAND_4}{Yeah.  Well you don't
 #live here.  There's nothing interesting to do, and believe you me, Brahma
 #Tipping gets old real fast.}
{118}{TAND_4}{是啊。幸好你不在这儿生活。相信我，这里没什么好玩的，双头牛老的很快。}
#{119}{}{If you're so bored, why don't you leave?}
{119}{}{如果你很无聊，为什么不离开呢？}
#{120}{}{Well, I'm sure you're exaggerating.}
{120}{}{我确定你在吹牛。}
#{121}{}{It seems nice and safe here.}
{121}{}{看起来这里很不错很安全。}
# {122}{TAND_5}{Me, leave?  I wish.  I don't know
# enough to leave alone and no one else wants to go, and worst of all, my father
# says he would have a heart attack if something happened to me! }
{122}{TAND_5}{我，离开？我很想离开。可我不知道怎样一个人离开，而且连个伴都没有。最糟糕的是，我爸爸说如果我出了什么事他会很伤心的！}
#{123}{}{Tough situation. Can I ask you a few questions, though?}
{123}{}{我还可以问你一些问题吗？}
#{124}{}{Shoot, I have to go. Good luck.}
{124}{}{我要走了。祝你好运。}
#{125}{TAND_6}{Uh...I have to stand over here now. }
{125}{TAND_6}{嗯……我现在不得不呆在这里。}
#{126}{TAND_12}{You live here all your life and see how you like it!  Anything
# else you want to know?}
{126}{TAND_12}{你在这里生活了一辈子，看看你都喜欢些什么！还有什么你想要知道的？}
#{127}{TAND_13}{Yeah, real safe...and so boring I think my brain's going to
# leak out of my ear at any moment.}
{127}{TAND_12}{耶，真的很保险……我左耳进右耳出的毛病真的很讨厌。}
#{128}{}{Why don't you leave?}
{128}{}{为什么你不离开？}
#{129}{}{Sorry to hear that, but I don't have much time.
 # Can I ask you a few questions?}
{129}{}{很抱歉听到那消息，但我的时间有限。我可以问你一些问题吗？}
# {130}{TAND_14}{Finally!  Someone else who
 # sees! Of course, you've probably been everywhere, so this must be hell for
 # you.}
{130}{TAND_14}{很好！谁看到其他人了！虽然你到过许多地方，但这里将会是你的地狱。}
# {131}{}{If you're so bored, why don't you leave?}
{131}{}{如果你很无聊，为什么不离开呢？}
#{132}{}{Well, I'm sure you're exaggerating.}
{132}{}{很好，我认为你在吹牛。}
#{133}{}{It seems nice and safe here.}
{133}{}{看起来它在这里很安全。}
# {134}{TAND_15}{Junktown's to the southwest, but I don't know how far.
 # Then there's some weird place below that called the City of Death.  Oh, oh
 # yeah there's this other place...Oh, shoot, what was that?  Oh, yeah, the
 # Hub.}
{134}{TAND_15}{迦克镇在南方，但我不知道有多远。然后下面这些奇怪的地方叫晒骨场。哦，哦，这里是另一个地方……哦，等等，那是什么？哦，对了，是哈勃城。}
# {135}{tand_15a}{There's a bunch of cities down south.  But since you're such a
 # great traveler, I'm sure you know that already.}
{135}{tand_15a}{南方有好几个城市。凭你这么一个出色的旅行者，我相信你早就知道了。}
# {136}{}{Thanks.}
{136}{}{谢谢。}
# {137}{TAND_16}{No problem. Anything else?}
{137}{TAND_16}{没问题。还有别的吗？}
# {300}{tand_16a}{Yeah, whatever.}
{300}{tand_16a}{是的，无论什么。}
# {138}{TAND_20}{We got Rad
 # Scorpions!  I mean, I know it's not a good thing, but no one's died from the
 # stings.  And it's the closest thing to excitement we've got here!}
{138}{TAND_20}{我们在抓大蝎子！我知道它不是什么好东西，但是没有人因为它们而死亡。抓他们很刺激，这正是吸引我们到这里来的原因！}
# {139}{TAND_21}{Nothing much, since you whomped those Rad Scorpions. Gee, I
 # wish I could have seen that.}
{139}{TAND_21}{非常少，自从你击溃了那些大蝎子后就不多了。前进！我希望看看你是如何收拾那些辐射蝎的。}
# {140}{TAND_22}{Same as always.  Bo-ring.}
{140}{TAND_22}{跟往常一样。无——聊。}
# {142}{tand_23b}{Just stuff.}
{142}{tand_23b}{废话。}
# {141}{tand_23g}{The weirdest story I've heard is about the Death Claw.}
{141}{tand_23g}{我听到的最精彩的故事是关于死亡爪的。}
# {143}{}{Thanks.}
{143}{}{谢谢。}
# {144}{}{Deathclaw?}
{144}{}{死亡爪？}
# {145}{TAND_24}{It's okay, I guess.  I mean, it is home and all, but it's so
 # boring!  You know, I want to see the world.}
{145}{TAND_24}{我想，那好吧。我的意思是，它是家，是所有一切，但太无聊啦！我想到外面的世界闯荡。}
# {146}{}{If you're so bored, why don't you leave?}
{146}{}{如果你很无聊，为什么不离开呢？}
# {147}{}{Well, I'm sure it's not that bad.}
{147}{}{好的，我确定它不是想象中的那么遭。}
# {148}{}{It seems nice and safe here.}
{148}{}{这里看起来很安全很不错。}
# {150}{tand_27f}{Listen...uh...but I...uh...I-I like guys, okay?  Whew!  Uh,
 # excuse me, I got stuff to do.}
{150}{tand_27f}{听着……唔……但我……唔……我……我喜欢大家，吆！唔，原谅我，我太忙了。}
# {149}{tand_27m}{I'm not that kind of girl,
 # mister. Go find a Brahma or something.}
{149}{tand_27m}{我不是那种女孩，先生。去找个双头牛或者其他什么东西吧。}
# {151}{TAND_28}{Well, thanks for talking.
 # We don't get many strangers here, so it's always good to talk to new people.
 # Well, see ya! }
{151}{TAND_28}{好，很高兴与你谈话。我们这里不经常来陌生人，所以大家总是和新来的打招呼。年轻人，很高兴见到你！}
# {152}{}{'Bye.}
{152}{}{再见。}
# {153}{TAND_29}{Uh, listen.  I have to go take care of the
 # Brahmas.  It was, uh, nice talking to ya. }
{153}{TAND_29}{唔，听着。我要去照顾那些双头牛。唔，很高兴和你谈话。}
# {154}{tand_30a}{Hello again!  What
 # can I help you with now?}
{154}{tand_30a}{再次欢迎！有什么能帮你的吗？}
# {155}{}{Can I ask you a few more questions?}
{155}{}{我能问你些问题吗？}
# {156}{}{Nothing. Goodbye.}
{156}{}{没什么。再见。}
# {157}{TAND_35}{Uh...hey, thanks. Later.}
{157}{TAND_35}{唔……嗨，谢谢。待会见。}
# {158}{TAND_36}{Hi!  I was afraid that you
 # were gone and I wasn't going to get a chance to thank you for rescuing me.
 # Aw!  That was great!  Action, adventure...Anyway, if there's anything that I
 # can do for you, you just ask.}
{158}{TAND_36}{嗨！我怕你走以后就没机会来感谢你救了我。嗯……好吧！战斗，冒险……总之，只要我能帮你的，你尽管开口。}
# {159}{}{How about a few more questions?}
{159}{}{能问些问题吗？}
# {160}{}{How about you and I...well, you know...get together.}
{160}{}{关于你和我……好吧，你知道的……在一起。}
# {161}{}{Nope, that's it, thanks.}
{161}{}{不是，那是，谢谢。}
# {162}{}{Dungh!!}
{162}{}{住手！！！}
# {163}{TAND_37}{Who are you?  What do you want?}
{163}{TAND_37}{你是谁？想干什么？}
# {164}{}{My name is }
{164}{}{我的名字是}
# {165}{}{, and your father sent me.}
{165}{}{，你父亲叫我来的。}
# {166}{}{I'm your fairy god-mother. What's it look like?}
{166}{}{我是你天使般的母亲。它像什么？}
# {167}{}{Duh.}
{167}{}{咄。}
# {168}{TAND_38}{Father sent you!?  Are you here to get me out?}
{168}{TAND_38}{爸爸叫你来的？！你要把我救走？}
# {169}{}{Yes, so just sit tight. I'll get you out.}
{169}{}{是的，就是这样。我是来救你的。}
# {170}{}{No, he just sent me to look at you.}
{170}{}{不，他只是让我来看看你。}
#{171}{TAND_39}{Well, what's your plan?}
{171}{TAND_39}{好吧，你打算怎么做？}
# {172}{}{Just wait for the doors to open. Then run for it!}
{172}{}{在这等着，门开了以后跑出去！}
# {173}{}{I'm going to fight the Khan leader in exchange
 # for your freedom.}
{173}{}{我去攻击流浪者首领来拖延时间。}
# {174}{TAND_40}{That's it?  That's your plan.
 # Ugh!  All right.  But hurry.  I heard them talking and I didn't like their
 # plans. }
{174}{TAND_40}{什么！那就是你的计划。啊！好吧。不过要快。我听到他们谈话了而且我不喜欢他们的计划。}
# {175}{TAND_41}{You?  Fight him?  You
 # got to be kidding me!  [Sigh] Listen, if you come up with another plan, let me
 # know, okay? }
{175}{TAND_41}{你？攻击他们？你在和我开玩笑吗！【叹气】听着，如果你还有其它计划，告诉我，好吗？}
# {176}{TAND_42}{Oh, aren't we the sarcastic one?  Are you going to
 # get me out, or what!?}
{176}{TAND_42}{哦，这是讽刺吗？你想救我出去，还是有别的企图！？}
# {177}{}{Yeah. Just hold on, and when you see the door open, run for it.}
{177}{}{是的，在这等着，门开了以后，跑出去。}
# {178}{}{I'm going to fight the Khan leader in exchange for your freedom.}
{178}{}{我去攻击流浪者首领来拖延时间。}
# {179}{TAND_43}{Oh, it's you again! Are you going to get
 # me out?}
{179}{TAND_43}{哦，再说一遍！你想救我出去？}
# {180}{}{Yes, so just sit tight. I'll get you out.}
{180}{}{是的，就是这样。我是来救你的。}
# {181}{}{No, I'm just stopping by to say hi.}
{181}{}{不，我只是来带个话。}
# {182}{}{Duh.}
{182}{}{咄。}
# {183}{tand_43a}{Hello, anybody home?  Could you get me out of here?
 # Could you GET ME OUT OF HERE!}
{183}{tand_43a}{你好，还有人在家吗？你要救我出去吗？你想要救我出去！}
# {184}{tand_43b}{This is no time to talk, we have to get out of here.}
{184}{tand_43b}{没有说话的时间了，让我们离开这里。}
# {185}{TAND_44}{Aradesh is my father.  He's okay, as far as dad's go.}
{185}{TAND_44}{亚拉德什是我爸爸。他回来的时候，身体很好。}
# {186}{TAND_45}{That's me.  Who else did you think it was?}
{186}{TAND_45}{是我。你以为是谁？}
# {187}{TAND_46}{Razlo's the old guy on the east side of town.  He's a pretty
 # good doctor, though, even if he is a fossil. }
{187}{TAND_46}{罗兹是镇东边的一个老家伙。他是个漂亮的好医生，虽然他很守旧。}
# {188}{TAND_47}{Seth's the captain of the guards.  My father tried to set
 # us up once, but he is not my type.}
{188}{TAND_47}{赛思是警卫队长。我爸爸曾经撮合过我们，但他不是我喜欢的类型。}
# {189}{TAND_48}{Agatha's the oldest one here.  We all love her, especially
 # her stories.  Go by and see her if you want a good yarn.}
{189}{TAND_48}{阿加莎是这里年纪最大的。我们都喜欢她，尤其是她的故事。如果你想听有趣的故事就去找她。}
# {190}{TAND_49}{Pretty
 # bad bunch or so I've heard.  My father knows more about them.  He never tells
 # me much about the outside world.}
{190}{TAND_49}{我听说过这样的坏事。我爸爸知道更多事。但他从不告诉我外面的事情。}
# {191}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{191}{TAND_50}{那是我们取水的地方。在我出生之前就有了。}
# {192}{TAND_51}{I've actually seen one, even if it was from far away. They're
 # nasty creatures, with claws and a big stinger.  And their poison can be
 # deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 # more about them. }
{192}{TAND_51}{即使在很远的地方，我也见到过一个。他们是肮脏的动物，有巨大的尾巴和锋利的毒刺，它们的毒即使处理过仍然会致命。你该去问我爸爸，亚拉德什，他知道它们的一些情况。}
# {193}{TAND_52}{I heard a tale from a traveller up from the south.  He said the
 # Death Claw was a creature that killed people at night.  He said no one can
 # catch it, because it can disappear like smoke.  Not that I believe it, of course.}
{193}{TAND_52}{我听过南边来的旅行者的故事。他说死亡爪是种在晚上杀人的动物。他说没有人能抓到它，因为它会像烟一样消失。当然，我不相信。}
# {194}{TAND_53}{Junktown's a small city to the southwest. It's supposed to
 # have pretty good trading, but my father won't even look into it.  He says we
 # need to stay 'protected'.  Yeah, right.  Caged is more like it. }
{194}{TAND_53}{迦克镇是西南方的一个小城。它的贸易很发达，但我爸爸不带我去。他说我需要“保护”。是的，很好，就像牢笼一样。}
# {195}{TAND_54}{The Hub is supposed to be a great city to the south.  I've
 # always wanted to see it, but I've never got the chance. }
{195}{TAND_54}{哈勃城是南方最大的城市。我很想去见识见识，但我从没有机会。}
# {196}{TAND_55}{I don't
 # know, but the guy who told me about it was really scared of it.  He said that
 # the undead walked the streets! }
{196}{TAND_55}{我不知道，但那家伙告诉我那里很恐怖。他说那里抓人做妓女！}
# {197}{TAND_62}{I don't know.  You might want to ask Seth or my father about it, though.}
{197}{TAND_62}{我不知道，但是，你可以问赛思或者我爸爸。}
# {198}{TAND_63}{Hmm...Doesn't ring a bell. }
{198}{TAND_63}{呃……不要反复的问这些没用的。}
# {199}{TAND_64}{Hm...nope.  I never heard of it. }
{199}{TAND_64}{嗯……不。我从没听说过。}
# {200}{TAND_65}{Hey!  What do you think you're doing?  Put that back! }
{200}{TAND_65}{嗨！你在做什么？离开那里！}
# {201}{TAND_66}{That's it!  I'm going to tell my father! }
{201}{TAND_66}{那就是了！我要告诉我爸爸！}
# {202}{TAND_67}{What the hell do you think you're doing?  Stop that! }
{202}{TAND_67}{你那样做不会下地狱吗？住手！}
# {203}{TAND_68}{What are you doing here? You better leave
 # before my father wakes up.}
{203}{TAND_68}{你在这做什么？你最好在我爸爸醒来之前离开。}
# {204}{TAND_69}{Like I said...}
{204}{TAND_69}{就像我说的那样……}
# {205}{TAND_70}{Listen, I already told you... }
{205}{TAND_70}{听着，我已经告诉你了……}
# {206}{TAND_71}{Again?  Hello?  How many times have I
 # have to tell you this?  You have too much wax in your ears or something?}
{206}{TAND_71}{还有？喂？我有多少时间总陪你聊天？你的耳朵聋了吗？}
# {207}{TAND_72}{Oh yeah, I heard of that, but you should go talk to Agatha.
 # She'd know more than I would.}
{207}{TAND_72}{哦耶，我听到了，但你应该去问阿加莎。她知道的比我多。}
# {208}{}{Let's get outta here.}
{208}{}{让我们离开这里。}

# {300}{}{Wow! This is nothing like Shady Sands.}
# {301}{}{Hey, what's that over there?}
# {302}{}{I can't wait to tell people in Shady Sands about the outside world.}
# {303}{}{You seen any more radscorpions?}
# {304}{}{Where are we going now?}
# {305}{}{When are we going to get there?}
{300}{}{哇！这里一点也不像沙荫镇。}
{301}{}{嗨，这附近有什么？}
{302}{}{我不能呆在沙荫镇给人们说外面的故事。}
{303}{}{你看到几只大蝎子吗？}
{304}{}{我们要去哪里？}
{305}{}{我们什么时候到那里？}


# {980}{TAND_62}{I don't know.  You might want to ask Seth or my father about it, though.}
# {981}{TAND_63}{Hmm...Doesn't ring a bell. }
# {982}{TAND_64}{Hm...nope.  I never heard of it. }
{980}{TAND_62}{我不知道，但是，你可以问赛思或者我爸爸。}
{981}{TAND_63}{呃……不要反复的问这些没用的。}
{982}{TAND_64}{嗯……不是。我从没听说过。}

# {1000}{}{亚拉德什}
# {1001}{}{坦蒂}
# {1002}{}{赛思}
# {1003}{}{袭击者}
# {1004}{}{井}
# {1005}{}{一些蝎子}
# {1006}{}{死爪}
# {1007}{}{迦克镇}
# {1008}{}{哈勃城}
# {1009}{}{城市}
# {1010}{}{蝎子}
# {1011}{}{流浪者}

{1000}{}{Aradesh}
{1001}{}{Tandi}
{1002}{}{Razlo}
{1002}{}{Seth}
{1003}{}{Raiders}
{1004}{}{Well}
{1005}{}{Scorpions}
{1006}{}{Claw}
{1007}{}{Junktown}
{1008}{}{Hub}
{1009}{}{City}
{1010}{}{Scorpion}
{1011}{}{Khans}

# {1000}{}{a}
# {1001}{}{b}
# {1002}{}{c}
# {1002}{}{d}
# {1003}{}{e}
# {1004}{}{f}
# {1005}{}{g}
# {1006}{}{h}
# {1007}{}{i}
# {1008}{}{j}
# {1009}{}{k}
# {1010}{}{l}
# {1011}{}{m}

# {1100}{TAND_44}{Aradesh is my father.  He's okay, as far as dad's go.}
{1100}{TAND_44}{亚拉德什是我爸爸。他回来的时候，身体很好，他会这样一直到老。}
# {1101}{TAND_45}{That's me.  Who else did you think it was?}
{1101}{TAND_45}{是我。你以为是谁？}
#{1102}{TAND_46}{Razlo's the old guy on the east side of town.  He's a pretty（注释）
# good doctor, though, even if he is a fossil. }（注释）
# {1102}{TAND_47}{Seth's the captain of the guards.  My father tried to set
 # us up once, but he is not my type.}
{1102}{TAND_47}{赛思是警卫队长。我爸爸曾经撮合过我们，但他不是我喜欢的类型。}
# {1103}{TAND_49}{Pretty bad bunch or so I've heard.  My father knows more
 # about them.  He never tells me much about the outside world.}
{1103}{TAND_49}{我听说过这样的坏事。我爸爸知道更多事。但他从不告诉我外面的事情。}
# {1104}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{1104}{TAND_50}{那是我们取水的地方。在我出生之前就有了。}
# {1105}{TAND_51}{I've actually seen one, even if it was from far away. They're
 # nasty creatures, with claws and a big stinger.  And their poison can be
 # deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 # more about them. }
{1105}{TAND_51}{即使在很远的地方，我也见到过一个。他们是肮脏的动物，有巨大的尾巴和毒刺。即使处理过它们的毒仍然致命。你该去问我爸爸，亚拉德什，他知道它们的一些情况。}
# {1106}{TAND_52}{I heard a tale from a traveller up from the south.  He said the
 # Death Claw was a creature that killed people at night.  He said no one can
 # catch it, because it can disappear like smoke.  Not that I believe it, of course.}
{1106}{TAND_52}{我听过南边来的旅行者的故事。他说死亡爪是种在晚上杀人的动物。他说没有人能抓到它，因为它会像烟一样消失。当然，我不相信。}
# {1107}{TAND_53}{Junktown's a small city to the southwest. It's supposed to
 # have pretty good trading, but my father won't even look into it.  He says we
 # need to stay 'protected'.  Yeah, right.  Caged is more like it. }
{1107}{TAND_53}{迦克镇是西南方的一个小城。它的贸易很发达，但我爸爸不带我去。他说我需要“保护”。是的，很好，就像牢笼一样。}
# {1108}{TAND_54}{The Hub is supposed to be a great city to the south.  I've
 # always wanted to see it, but I've never got the chance. }
{1108}{TAND_54}{哈勃城是南方最大的城市。我很想去见识见识，但我从没有机会。}
# {1109}{TAND_55}{I don't know, but the guy who told me about it was really
 # scared of it.  He said that the undead walked the streets! }
{1109}{TAND_55}{我不知道，但那家伙告诉我那里很恐怖。他说那里抓人做妓女！}
# {1110}{TAND_51}{I've actually seen one, even if it was from far away. They're
 # nasty creatures, with claws and a big stinger.  And their poison can be
 # deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 # more about them. }
{1110}{TAND_51}{即使在很远的地方，我也见到过一个。他们是肮脏的动物，有着爪子和巨大的刺。即使处理过它们的毒仍然致命。你该去问我爸爸，亚拉德什，他知道它们的一些情况。}
# {1111}{TAND_49}{Pretty bad bunch or so I've heard.  My father knows more
 # about them.  He never tells me much about the outside world.}
{1111}{TAND_49}{我听说过这样的坏事。我爸爸知道更多事。但他从不告诉我外面的事情。}
