{100}{}{你看见艾丽娅，一个沙漠歹徒。}
{101}{}{我是可汗的艾丽娅。今天我有什么能帮你吗？}
{102}{}{我在找一个叫坦蒂的女孩。你见过她吗？}
{103}{}{吻你一下如何？}
{104}{}{为什么你们这帮歹徒攻击沙荫镇？}
{105}{}{不，谢了。}
{106}{}{呼哟！}
{107}{}{如果她是这些从沙荫镇来的女人中的其中一个的话，可能你应该在那里看看。现在走开，我还要把我这些刀磨锋利。}
{108}{}{亲亲这个！}
{109}{}{我们没有攻击沙荫镇的人。我们和他们来自同一个地方。这是唯一的方式让他们和我们分享！}
{110}{}{但是你们伤害他们的家畜还恐吓他们。}
{111}{}{我感觉很公平。}
{112}{}{嗯，是啊。我想我该走了。}
{113}{}{听起来你和他们一样窝囊。听着，如果他们有了任何饥荒的麻烦，那么是他们自己没有预先计划的过错。想想我们用自己的才能和他们交易。}
{114}{}{用才能交易？！？这怎么会是用才能来交换？你们没有给他们任何东西。}
{115}{}{嗯，没错，如果鸡也会有三条腿的话。}
{116}{}{嗯，好吧。我想现在我该走了。}
{117}{}{我很抱歉，但是我听不懂你在说什么。我正在磨锋利我这些刀，而且我不喜欢被打扰。}
{118}{}{我给他们可能的最重要的东西。我们给他们枯燥的生活添加刺激。}
{119}{}{我不认为他们想要你们这种刺激。}
{120}{}{我想我会使他们的生活再次无聊。我将从你开始！}
{121}{}{嗯，是啊。我想我现在该走了。}
{122}{}{我没有要求他们要。不过既然你显然不具有任何娱乐的概念。我想我会了结你。}
{123}{}{嘲笑我预示着你的兆头不妙。我建议你离开我这里。}
{124}{}{该死的这当然公平。现在从我眼前滚开。}
{125}{}{我现在正忙于准备我们下一次的突袭。}




