{100}{}{你看见艾丽娅，一个沙漠强盗。}
{101}{}{我是可汗的艾丽娅。今天我有什么能帮你吗？}
{102}{}{我在找一个叫坦蒂的女生。你见过她么？}
{103}{}{吻你一下如何？}
{104}{}{为什么你们这帮歹徒攻击荒漠小镇？}
{105}{}{不，谢了。}
{106}{}{呼哟!}
{107}{}{如果她是这些从荒漠小镇来的女人中的其中一个的话，可能你应该在那里看看。现在走开，我还要把我这些刀磨锋利。}
{108}{}{亲亲这个！}
{109}{}{我们没有攻击荒漠小镇的人。我们和他们来自同一个地方。这是唯一的方式让他们和我们分享！}
{110}{}{但是你们伤害他们的家畜还恐吓他们。}
{111}{}{我感觉很公平。}
{112}{}{嗯，是啊。我想我该走了。}
{113}{}{听起来你和他们一样窝囊。听着，如果他们有了任何饥荒的麻烦，那么是他们自己没有预先计划的过错。想想我们用自己的才能和他们交易。}
{114}{}{用才能交易？！？这怎么会是用才能来交换？你们没有给他们任何东西。}
{115}{}{嗯，没错，如果鸡也会有三条腿的话。}
{116}{}{嗯，好吧。我想现在我该走了。}
{117}{}{我很抱歉，但是我听不懂你在说什么。我正在磨锋利我这些刀，而且我不喜欢被打扰。}
{118}{}{我给他们可能的最重要的东西。我们给他们枯燥的生活添加刺激。}
{119}{}{我不认为他们想要你们这种刺激。}
{120}{}{我想我会使他们的生活再次无聊。我将从你开始！}
{121}{}{嗯，是啊。我想我现在该走了。}
{122}{}{我没有要求他们要。不过既然你显然不具有任何娱乐的概念。我想我会了结你。}
{123}{}{嘲笑我预示着你的兆头不妙。我建议你离开我这里。}
{124}{}{该死的这当然公平。现在从我眼前滚开。}
{125}{}{我现在正忙于准备我们下一次的突袭。}




#{100}{}{You see 艾丽娅, a desert raider.}
#{101}{}{I am 艾丽娅 of the Khans. How might I help you today?}
#{102}{}{I'm looking for a woman named 坦蒂. Have you seen her?}
#{103}{}{How about a little kiss?}
#{104}{}{Why has your band of 歹徒 attacked 荒漠小镇?}
#{105}{}{No, thank you.}
#{106}{}{Hooroo!}
#{107}{}{If she is one of those women from 荒漠小镇, maybe you should look there. Now go, I need to finish sharpening my knives. }
#{108}{}{Kiss this!}
#{109}{}{We do not attack those of 荒漠小镇. We are from the same place they are. It is only right that they share with us!}
#{110}{}{But you are hurting their livestock and terrifying them.}
#{111}{}{That seems fair to me.}
#{112}{}{Uh, yeah. I think I will be going now.}
#{113}{}{You sound just as wimpy as they are. Look, if they were in any trouble of starvation, then it is their own fault for not planning ahead. Consider what we do a trade in talents.}
#{114}{}{A trade in talents?!? How can this be a trade in talents? You don't give them anything.}
#{115}{}{Sure, and chickens have three legs.}
#{116}{}{Uh, yeah. I think I will be going now.}
#(117}{}{I am sorry, but I can't understand you. I'm sharpening my knives and would not like to be bothered.}
#{118}{}{We give them the most important thing possible. We give their dreary lives excitement.}
#{119}{}{I don't think they want your type of excitement.}
#{120}{}{I think I will make their lives boring again. I'll start with you!}
#{121}{}{Uh, yeah. I think I will be going now.}
#{122}{}{I didn't ask. But since you obviously don't have any concept of fun, I think I will end your existence.}
#{123}{}{Mocking me does not bode well for you. I suggest you leave my presence.}
#{124}{}{Darn straight that it's fair. Now get out of my face.}
#{125}{}{I am busy right now preparing for our next raid.}