
#
# Talking cows special encounter text
#


#{100}{}{Moo.}
{100}{}{哞！你真的只有一个头！没有进化出两个头可真够悲哀的。}

#{101}{}{Moo!}
{101}{}{哞！在我的身体里就有一个净水芯片，但是杀了我，你也拿不到。不要妄想灭了我们的种族，我们无处不在，连奥秘大陆上也有我们的存在。}

#{102}{}{Moo, I say.}
{102}{}{哞！不要再点了，黑岛并没有给我分配台词！并且，双头牛的尊严不允许我们使用人类的语言！}

#{103}{}{It's a wild Brahmin.}
{103}{}{那是一只野生双头牛。奇怪的，它在紧紧的盯着你，好像它能听懂你说的话。}

#{104}{}{There is nothing natural about these cows. The second head can only be the result of some strange mutation.}
{104}{}{这些牛不是原来就这样的。第二个脑袋显然是辐射变异的结果。}

#{105}{}{Looks pretty normal to you.}
{105}{}{看起来似乎很正常。}



