#{100}{}{You see Sister Francis.}
#{101}{}{Hi! Oh, it's you! I hope you're not here to kill me. If you don't mind, could you wait until after I finish meditating?}
#{102}{}{Oh, it's you again. I don't mean to be rude, but I am meditating . . .}
#{103}{}{Excuse me, could you put away your weapon? I can't meditate on peace when I'm, like, uh, staring certain death in the face. Thank you very much.}
#{104}{}{You know, there are people who say really bad things about you. You ought to do something about that . . .}
#{105}{}{Hi. I'm meditating. Did you notice? Can I help you?}
#{106}{}{Sure. You notice anything unusual around here?}
#{107}{}{Care to share any favorite meditations with me?}
#{108}{}{Who's in charge here?}
#{109}{}{Where can I find the Master?}
#{110}{}{I'm looking for large quantities of liquor. I'd like to remove them from the premises . . .}
#{111}{}{Got any ammo?}
#{112}{}{Hep! Me hep?}
#{113}{}{Hello, brother. Can I help you?}
#{114}{}{Hello, sister. Can I help you?}
#{115}{}{Sure. You notice anything unusual around here?}
#{116}{}{Care to share any favorite meditations with me?}
#{117}{}{Who's in charge here?}
#{118}{}{Where can I find the Master?}
#{119}{}{I'm looking for large quantities of liquor. I'd like to remove them from the premises . . .}
#{120}{}{Got any ammo?}
#{121}{}{Hep! Me hep?}
#{122}{}{Sure. You notice anything unusual around here?}
#{123}{}{Care to share any favorite meditations with me?}
#{124}{}{Who's in charge here?}
#{125}{}{Where can I find the Master?}
#{126}{}{I'm looking for large quantities of liquor. I'd like to remove them from the premises . . .}
#{127}{}{Got any ammo?}
#{128}{}{Hep! Me hep?}
#{129}{}{Well, Father Morpheus hasn't given any sermons in such a long time. It's a pity, because I so love his speeches and everybody seems to be very busy with some Crusade.}
#{130}{}{Now, if you'll excuse me, I must go back to meditating.}
#{131}{}{Why I could, but the ones who go through the Servitor process are so much better than I am . . . Their minds are so much more focused on the Master than mine. Maybe after I get changed, I'll get better.}
#{132}{}{Now, if you'll excuse me, I must go back to meditating.}
#{133}{}{Why, that's Father Morpheus. He's such a good speaker, he really makes Peace and Unity come to life, and when he talks, I can just see those Holy Flames!}
#{134}{}{That Father Morpheus, he sure can talk; and he's handsome, too!}
#{135}{}{I think that's one of the Inner Mysteries that the priests discuss upstairs in the Inner Sanctum. I have not been privileged enough for that revelation yet, but I'm working at it!}
#{136}{}{Now, if you'll excuse me, I must go back to meditating.}
#{137}{}{My goodness! Alcohol and drugs here! You must be mistaken. The Master would never tolerate it. He wants all of his followers to keep their minds healthy and pure.}
#{138}{}{Now, if you'll excuse me, I must go back to meditating.}
#{139}{}{I think holy ammunition is available in the Cathedral Gift Shoppe . . .}
#{140}{}{Now, if you'll excuse me, I must go back to meditating.}
#{141}{}{Why no. No help at all. Goodbye.}
#{142}{}{Hello, brother. No, I've been meditating like a good initiate, waiting to be christened by the Servitors. I'm sure there's nothing to worry about.}
#{143}{}{Hello, sister. No I've been meditating like a good initiate, waiting to be christened by the Servitors. I'm sure there's nothing to worry about.}
#{144}{}{The Master is my friend. Unity is prosperity. Peace is prosperity. Peace and Unity come through Obedience. Obedience is proven through Submission to Authority . . .}
#{145}{}{He who submits will be christened by the Holy Flame, but the faithful will not be burned. He who goes through Fire without burning shall have life everlasting . . .}
#{146}{}{I hope I didn't miss anything . . .}
#{147}{}{Is this a trick question? It's the Master, right?}
#{148}{}{Well I've heard that the Master can be found in Holy Fire, that he waits below for Unity and Peace, and he lives in the hearts and minds of all virtuous people . . .}
#{149}{}{I'm not sure which of these is a metaphor. Maybe he's everywhere.}
#{150}{}{Why brother, nothing so impure profanes the Cathedral. I would let the high priests know if such sins were being committed.}
#{151}{}{Why sister, nothing so impure profanes the Cathedral. I would let the high priests know if such sins were being committed.}
#{152}{}{I am armed, of course, if reason will not sway our enemies, but I do not arm myself to excess. Is there no ammo in the Gift Shoppe?}
#{153}{}{Oh no, brother, I do not require assistance. Please excuse me.}
#{154}{}{Oh no, sister, I do not require assistance. Please excuse me.}
#{155}{}{Well, I am told that the Peace and Unity we seek for all creatures is unusual, but I hope this will not be the case for much longer.}
#{156}{}{Now, if you'll excuse me, I must go back to meditating.}
#{157}{}{I don't know. Perhaps he will reveal himself in time.}
#{158}{}{[done]}
#{159}{}{[more]}
#{160}{}{Hello, sir. Can I help you?}
#{161}{}{Hello, miss. Can I help you?}


{100}{}{你看到弗朗西斯修女。}
{101}{}{嗨！噢，是你呀！我希望你别杀我，如果你不介意，至少等我做完祷告再动手。}
{102}{}{喔，又是你，请原谅我的无理，因为我正在做祷告…}
{103}{}{对不起，你能收起你的武器吗？如果没有平和的气氛我就不能祈祷了，恩，不过我会正视死亡的，非常感谢你。}
{104}{}{你知道吗？那的人在说你的坏话。你应该对此做出写回映…}
{105}{}{嗨，我在祷告。你没注意到吗？有什么需要帮忙的吗？}
{106}{}{当然，你有没有注意到附近有什么怪异的事情吗？}
{107}{}{在意和我一起分享祈祷的幸福吗？}
{108}{}{谁是这里的主管?}
{109}{}{哪能找到主教？}
{110}{}有什么喝的没有？我想拿点回去…}
{111}{}{有弹药吗？}
{112}{}{啊！我怎么可能知道？}
{113}{}{你好，兄弟。需要我帮忙吗？}
{114}{}{你好，姐妹。需要我帮忙吗？}
{115}{}{当然，你有没有注意到附近有什么怪异的事情吗？}
{116}{}{在意和我一起分享祈祷的幸福吗？}
{117}{}{谁是这里的主管?}
{118}{}{哪能找到主教？}
{119}{}{有什么喝的没有？我想拿点回去…}
{120}{}{有弹药吗？}
{121}{}{啊！我怎么可能知道？}
{122}{}{当然，你有没有注意到附近有什么怪异的事情吗？}
{123}{}{在意和我一起分享祈祷的幸福吗？}
{124}{}{谁是这里的主管?}
{125}{}{哪能找到主教？}
{126}{}{有什么喝的没有？我想拿点回去…}
{127}{}{有弹药吗？}
{128}{}{啊！我怎么可能知道？}
{129}{}{我们的神父睡梦之神墨菲斯已经好久没有布道了。太遗憾了，我太热忠他的讲演了，可是每个人似乎都在忙着搞什么圣战。}
{130}{}{如果你现在不介意的话，我要回去祷告了。}
{131}{}{为什么我可以？别人比我更虔诚，他们的思想和主教的思想已经融会贯通了，也许以后我变的更好。}
{132}{}{如果你现在不介意的话，我要回去祷告了。}
{133}{}{那可是神父墨菲斯，他的讲演太精彩了，世界大同在他的口中仿佛真的实现了一样，并且当他讲话的时候我还能看到他背后燃起了圣火！}
{134}{}{那个神父墨菲斯，他不光口才好而且还很英俊。}
{135}{}{我认为那些核心牧师的聚会都在二楼的密实里展开的，但是我没有足够的特权进去参与其中，我仍然在为此而努力研究！}
{136}{}{如果你现在不介意的话，我要回去祷告了。}
{137}{}{我的天那！酒和毒品！你犯了大错误。主教是不会容忍的！他要所有他的信徒都要洁身自好，怎么能沾这些脏东西！}
{138}{}{如果你现在不介意的话，我要回去祷告了。}
{139}{}{我认为那些神圣的武器可以在大教堂的礼品店买到…}
{140}{}{如果你现在不介意的话，我要回去祷告了。}
{141}{}{你根本帮不上忙，再见。}
{142}{}{你好，兄弟。不，我的祷告就是要打个好基础，我随时等候着更高层次的洗礼，我确实没什么好担心的。}
{143}{}{你好，姐妹。不，我的祷告就是要打个好基础，我随时等候着更高层次的洗礼，我确实没什么好担心的。}
{144}{}{教主是我的朋友。统一就会昌盛，和平就会繁荣。和平统一的前提是服从，对权威的绝对服从…}
{145}{}{他们的真诚要经过圣火洗礼的考验，只有忠实的信徒才不会被燃烧，他们的生命将得到永恒。}
{146}{}{我希望我没有错过任何事…}
{147}{}{这是主教编织的一个骗局，对吧？}
{148}{}{我听说在圣火中可以看到主教，他在等待和平统一的降临，他活在所有善良的人民心中。}
{149}{}{我不确信那些那一个是隐喻，也许全都是把。}
{150}{}{兄弟，你怎么可以如此亵渎大教堂，如果真有邪恶的事物存在，我会上报主教的。}
{151}{}{姐妹，你怎么可以如此亵渎大教堂，如果真有邪恶的事物存在，我会上报主教的。}
{152}{}{如果不能说服我的敌人我就要用武力，但是我的装备还不够，礼品店里没弹药吗？}
{153}{}{噢不，兄弟，我不需要援助。请原谅。}
{154}{}{噢不，姐妹，我不需要援助。请原谅。}
{155}{}{我知道我们寻求和平与统一在人们眼力是多么的不正常，我只希望这样的误解不要持续太久。}
{156}{}{如果你现在不介意的话，我要回去祷告了。}
{157}{}{我不知道，也许到时间他会暴露他自己的。}
{158}{}{【完成】}
{159}{}{【更多】}
{160}{}{你好，先生。我能帮助你吗？}
{161}{}{你好，小姐。我能帮助你吗？}