# {100}{}{Die, you dog!}
# {101}{}{My defeat shall be avenged!}
# {102}{}{Hail, Initiate! I hope your patrols have fared well.}
# {103}{}{Hold! If you have not spoken with our Captain yet, do so and then go!}
# {104}{}{Hold! I recognize you and I do not trust you. I give you fair warning: if you make trouble for us, you will be shot dead. Now move!}
{100}{}{死吧，你这条狗！}
{101}{}{我会报仇的！}
{102}{}{很好新兵！我祝你巡逻顺利。}
{103}{}{立正！如果你还没有和我们的指挥官谈话，那么现在就去做吧。}
{104}{}{立正！我认识你但我不信任你。我给你个忠告：如果你给我们找麻烦，我就射死你，现在走吧！}