#{100}{}{You see a mad scientist. He is working diligently on something.}
{100}{}{你看见一位疯狂的科学家。他正在努力的工作。}

#{101}{}{Good evening, brother. What brings you to our little corner of heaven?}
{101}{}{晚安，兄弟。是什么带你来到我们天堂的小角落？}

#{102}{}{Good evening, sister. What brings you to our little corner of heaven?}
{102}{}{晚安，姐妹。是什么带你来到我们天堂的小角落？}

#{103}{}{I'm here to check on your progress.}
{103}{}{我是来检查你的进展。}

#{104}{}{What might you be doing here?}
{104}{}{你在这能做什么？}

#{105}{}{What?! You dare question me? How about I experiment on your brain,
# you twisted skag?!}
{105}{}{什么？！你敢询问我？我在你脑袋上做做实验怎么样？}

#{106}{}{Gack.}
{106}{}{呷呷。}

#{107}{}{You, again? And why are you disturbing the Master's glorious
# future this time?}
{107}{}{又是你？为什么这次你又来妨碍主教的光荣事业？}

#{108}{}{The Master grows impatient with your failures, and I with your
# impudence!}
{108}{}{主教对你的失败很不耐烦，而我对你的无礼也是！}

#{109}{}{I want to know what's happening with your experiments.}
{109}{}{我想要知道你的实验有什么。}

#{110}{}{That's it, I'm putting an end to YOUR future right here and now, chump!}
{110}{}{是，我就是让你的未来结束的，笨蛋！}

#{111}{}{Oofah!}
{111}{}{啊哈！}

#{112}{}{It's not going well. I've been injecting the FEV directly into the
# pineal gland, but I'm not getting the results I'd hoped for.}
{112}{}{进展并不顺利。我把ＦＥＶ直接注射到松果腺，但是没有得到我希望的结果。}

#{113}{}{Why don't you try injecting it  into the Amygdala?}
{113}{}{为什么你没试试把它直接注射到扁桃腺？}

#{114}{}{Why don't you try injecting it into the Medula?}
{114}{}{为什么你没试试把它注射到毛髓？}

#{115}{}{What results are you getting?}
{115}{}{你得到了什么结果？}

#{116}{}{Hmmm. And?}
{116}{}{呵呵。如何？}

#{117}{}{I beg your forgiveness, sir. How may I be of service?}
{117}{}{我请求你的宽恕，先生。我怎样才能帮助你？}

#{118}{}{I beg your forgiveness, ma'am. How may I be of service?}
{118}{}{我请求你的宽恕，夫人。我怎样才能帮助你？}

#{119}{}{You can speak to me with respect next time, or you'll never speak to
# anyone again!}
{119}{}{你下次跟我说话要尊敬点，否则你就再也无法讲话了！}

#{120}{}{The Master's truth is revealed, resulting in increased psychic
# ability. 【shakes his head】 But the poor souls become terminally insane and
# must be sequestered and nullified to keep them from harming themselves or
# others.}
{120}{}{主教真理显示, 那能造成精神能力的增强。【摇头】但是可怜的灵魂变得极端疯狂，只能将他们隔离，并且无法保证他们不伤害自己或其它人。}

#{121}{}{Oh, how thoughtful of you...}
{121}{}{哦，你真是深思熟虑啊．．．}

#{122}{}{Where are they being kept？}
{122}{}{他们被关在哪里？}

#{123}{}{You heartless butcher! I think I'll nullify your brain and sequester
# it from the rest of your body! Die, you bastard!}
{123}{}{你这个无情的屠夫! 我要挖出你的脑子看看什么样!去死，杂种！}

#{124}{}{In a room northwest of here. Is there anything else I can help you with?}
{124}{}{在这西北部的房间里。还有别的我能帮你吗？}

#{125}{}{Thank you for your help. Bye.}
{125}{}{谢谢你的帮助。再见。}

#{126}{}{Yeah, uh. What's FEV?}
{126}{}{呀，嗯。什么是ＦＥＶ？}

#{127}{}{You can die!}
{127}{}{去死！}

#{128}{}{I have no time for your tomfoolery!}
{128}{}{我没有时间理你愚蠢的举动！}

#{129}{}{What an intriguing idea! I must try it at once!}
{129}{}{迷人的想法！我必须立刻试试！}

#{130}{}{Uh, where are you keeping the failed experiments?}
{130}{}{呃，你实验的失败品在哪？}

#{131}{}{Don't mention it.}
{131}{}{不要提它。}

#{132}{}{Yeah! Let's try it on you!}
{132}{}{呀！让我们在你身上试试！}

#{133}{}{Vincent! Prepare our newest volunteer!}
{133}{}{文森特！准备我们最新的志愿者！}

#{134}{}{What? That's the most ludicrous thing I've ever heard! 【looks at
# you suspiciously】 Who are you, really?}
{134}{}{什么？那是我听到的最可笑的事！【怀疑的看着你】你到底是谁？}

#{135}{}{Oh, sorry. I've got to go now.}
{135}{}{哦，对不起。我现在必须走了。}

#{136}{}{I'm a new..uh...guy.... I've been sent to find out how you are doing.}
{136}{}{我是一个新．．．呃．．．人．．．我被派来看看你做得怎么样了。}

#{137}{}{I already told you, I've been sent by the Master to check up on you.}
{137}{}{我已经告诉了您，是主教派我来检查你的。}

#{138}{}{I've come to remove your spleen... without anesthetic!}
{138}{}{我必须去除你的脾脏．．．没有麻醉剂！}

#{139}{}{Alright, then. So how is it going?}
{139}{}{那么好吧，事情进展如何？}

#{140}{}{Your attitude has told me all I need to know. Goodbye.}
{140}{}{你的态度已经告诉我我需要知道的全部。再见。}

#{141}{}{Ah ha! An interloper! Just as I suspected. Vincent!}
{141}{}{啊哈！一个闯入者！正如我猜测的。文森特！}

#{142}{}{Who are you? And why are you wearing that suit? 【to himself】 I haven't
# seen one of those in a long time.}
{142}{}{你是谁？而且你为什么穿着那种衣服?【对他自己】我已经很久没有看到那些了。}

#{143}{}{I'm in disguise. Intruders have infiltrated the Master's sanctuary,
# and I'm dressed like one of them to gain their confidence.}
{143}{}{我是在伪装。入侵者已经渗入主教的庇护所，我穿着他们衣服以取得他们的信任。}

#{144}{}{How dare you question one of the Master's special operatives!}
{144}{}{你怎么胆敢询问主教的特派员！}

#{145}{}{When have you seen a suit like this before?}
{145}{}{你以前看见过像这样的衣服？}

#{146}{}{It's extruded rubber, so it's real easy to wipe your blood off after
# I kill you!}
{146}{}{就像挤橡皮，在我杀了你之后擦去你的血真是很容易。}

#{147}{}{Oh, you know, when we got that last batch of pure-strain humans in...
# I think there is still one in the holding pens. Why do you ask?}
{147}{}{噢，您知道，当时我们让最近一批纯种人类进入．．．我认为在拘押栏中还剩一个。你为什么要问这个？}

#{148}{}{No reason. How are the experiments going?}
{148}{}{没有理由。实验是如何进行的？}

#{149}{}{I've got to report back to the Master. I don't have time for this.}
{149}{}{我必须回去报告主教。我没有时间为这个。}

#{150}{}{【shakes his head】 Alas, the poor souls become terminally insane and
# must be sequestered and nullified to keep them from harming themselves or
# others.}
{150}{}{【摇头】呀，可怜的灵魂变得极端疯狂，只能将他们隔离，并且无法保证他们不伤害自己或其它人。}

#{151}{}{Oh, how thoughtful of you...}
{151}{}{噢，你想的真周到啊．．．}

#{152}{}{You heartless bastard! I think I'll nullify your brain and sequester
# it from the rest of your body! Die, you bastard!}
{152}{}{你这个冷血的杂种！我要挖出你的脑子看看什么样!去死，杂种！}

#{200}{}{You see Vincent, a super mutant guard. He looks bored.}
{200}{}{你看见文森特，一个超级变种人警卫。他看起来很无聊。}

#{201}{}{You see a super mutant, obviously guarding the scientists. He looks
# bored}
{201}{}{你看见一个超级变种人，明显在保卫科学家。他看起来很无聊。}

#{202}{}{Intruders!}
{202}{}{入侵者！}

#{203}{}{I'm just watching the mads. Don't talk to me.}
{203}{}{我正在守卫疯狂者。不要和我说话。}

#{204}{}{Leave me alone.}
{204}{}{别理我。}

#{300}{}{You see a sleeping mad scientist.}
{300}{}{你看见一位睡觉的疯狂科学家。}

#{301}{}{Zzzzzz}
{301}{}{ＺＺｚｚｚ}

#{302}{}{Huh! What? 【rubs eyes】 Vincent, remove this heathen from our chambers!}
{302}{}{哼！什么？【擦眼睛】文森特，把这个异教徒从我们的房间弄走！}

#{303}{}{Huh? 【snort】 ...zzzzzzzzz}
{303}{}{哼？【喷鼻息】．．．ｚｚｚｚｚｚ}

#{400}{}{You see Vincent. He is guarding the sleeping mads.}
{400}{}{你看见文森特．他正在守卫疯狂者。}

#{401}{}{You see a super mutant guard. He is nearly standing over the prone bodies.}
{401}{}{你看见一个超级变种人警卫。他站着几乎快睡着了。}

#{402}{}{Leave them alone, and get out. No one is allowed in here while they
# are sleeping.}
{402}{}{别管他们，离开这儿。当他们正在睡觉的时候，不允许有人在这里。}

#{403}{}{You again! I told you to leave the scientists alone!}
{403}{}{又是你！我告诉过你别打扰科学家！}

#{404}{}{You have overstayed your welcome.}
{404}{}{你已经逗留很久了。}

