#{100}{}{You see Mephisto, an angry merchant.}
#{101}{}{You see a merchant named Harms.}
#{102}{}{You see an upset merchant named Fowler.}
#{103}{}{You see Dixon, an angry merchant.}
#{104}{}{You see Morgan, a merchant.}
#{105}{}{You see Marco, an angry merchant.}
#{106}{}{You see Kjolnir, a merchant.}
#{107}{}{You see Marzen, a merchant.}
#{108}{}{You see Joshua, an upset merchant.}
#{109}{}{You see Anthony, a merchant.}
#{110}{}{You see Clark, a merchant.}
#{111}{}{You see Malantic, an upset merchant.}
#{112}{}{You see Orlando, a merchant.}
#{113}{}{You see a merchant named Ilya.}
#{114}{}{You see Tracy, an upset merchant.}
#{115}{}{Can you believe this chaos?}
#{116}{}{Get in line.}
#{117}{}{You're not of this house.}
#{118}{}{Have you had your caravan delayed too?}
#{119}{}{Good luck getting anything done.}
#{120}{}{Have you seen Hightower?}
#{121}{}{I'd see the Far Go Traders if I were you.}
#{122}{}{Looking for the master merchant? She's right over there.}
#{123}{}{If my cargo doesn't leave soon, there'll be hell to pay.}
#{124}{}{Martha's right over there.}
#{125}{}{You're no merchant, beat it.}
#{126}{}{The guard quarters are on the other side.}
#{127}{}{I'm not giving you any money, so leave.}
#{128}{}{My cargo is never going to leave.}
#{129}{}{Don't even think about moving in on my territory.}
#{130}{}{Why hasn't my cargo left yet?}
#{131}{}{Where are my supplies?}
#{132}{}{Your prices are terrible!}
#{133}{}{Where's Hightower?}
#{134}{}{I'm suppose to get priority!}
#{135}{}{My cargo's two weeks late!}
#{136}{}{I want my money back!}
#{137}{}{I want to speak with Hightower.}
#{138}{}{I'll take my business to the Crimson Caravan.}
#{139}{}{What's wrong with you people?}
#{140}{}{I'm tired of waiting!}
#{141}{}{I'm sick of excuses!}
#{142}{}{My cargo is more important than his!}
#{143}{}{What don't you understand?}
#{144}{}{Do it or I'll go elsewhere!}
{100}{}{你看见墨菲斯托，一个生气的商人。}
{101}{}{你看见一个叫哈姆斯的商人。}
{102}{}{你看见烦恼的商人福勒。}
{103}{}{你看见狄克逊，一个生气的商人。}
{104}{}{你看见摩根，一个商人。}
{105}{}{你看见马克，一个生气的商人。}
【106】【】【你看见卡佳尔，一个商人。}
{107}{}{你看见马恩，一个商人。}
{108}{}{你看见约书亚,一个烦恼的商人。}
{109}{}{你看见安东尼，一个商人。}
{110}{}{你看见克拉克，一个商人。}
{111}{}{你看见马兰狄克，一个烦恼的商人。}
{112}{}{你看见奥兰多，一个商人。}
{113}{}{你看见一个叫艾丽亚的商人。}
{114}{}{你看见特蕾西，一个烦恼的商人。}
{115}{}{你能相信这混乱吗？}
{116}{}{排队。}
{117}{}{你不是这房子里的。}
{118}{}{你也押后了你商队的行程吗？}
{119}{}{祝你好远。}
{120}{}{你有看到海塔尔吗？}
{121}{}{如果我是你就去找长途商人。}
{122}{}{找大当家的？她就在那里。}
{123}{}{如果我的货物不能马上发送，就会赔死了。}
{124}{}{玛莎就在那里。}
{125}{}{你不是商人，走开。}
{126}{}{这些守卫的住处就在另一边〉}
{127}{}{我是不会收你的钱，所以离开。}
{128}{}{我的货物决不能丢。}
{129}{}{别想搬到我的地盘里。}
{130}{}{为什么我的货物还在这？}
{131}{}{我的补给在哪？}
{132}{}{你的价格太糟糕！}
{133}{}{海塔尔在哪里？}
{134}{}{应该是我先的！}
{135}{}{我的货物迟到了两星期！}
{136}{}{我想要我的钱！}
{137}{}{我想见海塔尔先生。}
{138}{}{我将和深红商队做生意。}
{139}{}{你们是怎么回事？}
{140}{}{我等得不耐烦了！}
{141}{}{你不要再多解释了！}
{142}{}{我的货物比他的重要！}
{143}{}{你还有什么不懂的？}
{144}{}{要么买要么去别家。}