# {100}{}{You see Mike, the Old Town guard.}
# {101}{}{Yeah, whatta' you want?}
# {102}{}{a...dum...um...}
# {103}{}{I'm not from around here. What part of town is this?}
# {104}{}{Do you know where I can find a Water Chip?}
# {105}{}{Um... Bye.}
# {106}{}{Ha. Just another Junkie. Go crash somewhere else, Junkhead.}
# {107}{}{Yeah. You must be lost. Most people wouldn't be caught dead in this part of town. This is the Eastside, or some call it Old Town. The Wastes of the Wastes.}
# {108}{}{Do you know where I can find a Water Chip?}
# {109}{}{Thanks for the info.  Bye.}
# {110}{}{Water Chip? What are you? On dope? A chip made of water?}
# {111}{}{Don't you be mouthing off to me, punk. Now I'm gonna have to put you in the ground.}
# {112}{}{I'm not from around here. What part of town am I in?}
# {113}{}{Nevermind. Bye.}
{100}{}{你看到迈克，一个旧城区的守卫。}
{101}{}{是的，你需要什么？}
{102}{}{啊……哒……呣……}
{103}{}{我不是这附近的，请问这是城镇的哪个区？}
{104}{}{你知道在哪里能找到一个净水芯片吗？}
{105}{}{哦……再……见。}
{106}{}{哈，又一个吸毒的，到别的地方吸毒或干点什么去吧。}
{107}{}{哦，你一定是迷路了。这是城东区，又叫老城区，垃圾场中的垃圾场。城里大多数人不会到这里找死的。}
{108}{}{你知道在哪里能找到一个净水芯片吗？}
{109}{}{谢谢你的消息，再见。}
{110}{}{水芯片？你要那个干嘛？用来吸毒的？一个小芯片可以制造水？}
{111}{}{不用对我做鬼脸，你这个小流氓。我现在就把你放倒在地上。}
{112}{}{我不是这附近来的，请问这里是什么区？}
{113}{}{多加小心，再见。}