#{100}{}{You see Richie.}
{100}{}{你看见瑞奇。}

#{101}{}{You're not supposed to do that. I'm gonna have to stop you!}
{101}{}{你不能那么做。我会阻止你的！}

#{102}{}{You're not supposed to be here. Do you realize I'm supposed to kill you?}
{102}{}{你不能到这里，你不知道我会杀了你吗？}

#{103}{}{Your shift is over. I'm your replacement.}
{103}{}{你下班的时间到了，轮到我换班了。}

#{104}{}{Hub vault inspector. I'm here to inspect the vault. Move aside.}
{104}{}{哈勃城避难所的巡视员，我来巡视这个避难所。闪开。}

#{105}{}{Kid, fight it. End the cycle of violence now!}
{105}{}{小子，动手吧。现在做个了断！}

#{106}{}{Who told you that! Mister, if you attack me, it'll be the biggest mistake of your life!}
{106}{}{那是谁告诉你的！先生，如果你伤到我，那么你会后悔一辈子的。}

#{107}{}{Hi kid! What's in the steel vault?}
{107}{}{嘿，小子！在这个避难所里有什么？}

#{108}{}{Too late, punk. You're dead.}
{108}{}{太晚了，流氓。你死定了。}

#{109}{}{Uh?yeah?runk厎
{109}{}{嗯？是吗？喏咯。}

#{110}{}{I'm not supposed to be talking to you! Scram!}
{110}{}{我没法和你说了！滚开！}

#{111}{}{It's about time! It's hot in here! Boring too! If I didn't need this job to feed my family, I'd tell
# Lorenzo to stick it. See you tomorrow.}
{111}{}{到时间了！这里真热！太讨厌了！如果我不是需要这个活来养家户口的话，我建议罗仑佐来试试。明天见。}

#{112}{}{I'm not supposed to leave this place and you're not supposed to be here. Get out!}
{112}{}{我不想离开这里，而你也别想待在这。立刻离开！}

#{113}{}{You Hub officials make me sick! Inspecting my bosses' vault! What's next, higher taxes? Can't a man
# earn an honest living anymore without you bureaucrats trying to control everything? One of these days we're
# going to take a stand. Yeah, one of these days the common man is going to give you fatcats a knee to the
# balls like you deserve. One of these days we'll get you real good?I can't wait?By the way, it's not meant
# personal. I know you're just doing your job. I'll get out of your face while you do your inspection. Bye.}
{113}{}{你这个哈勃城的官员真让我不舒服！巡视我老板的避难所！往下呢，交些奇怪的税？没有你这种当官的管这管那我们就活不了吗？总有一天我们会站起来。是的。总有一天我们平民会一起踢你们当官的屁股。然后把你们的财产都拿走嗯？等不及这么干了，顺便说一下，不是我一个人想这么干。我知道你仅仅是执行公务。我不想再看着你这张脸，再见。}

#{114}{}{Don't give me this crap! Get outta here now or I'll have to shoot you!}
{114}{}{别跟我说这种废话！再不闪开我就开枪了！}

#{115}{}{Oh yeah. Well no one pushes around Richie Glowsteader and gets away with it!}
{115}{}{哦太好了。胆敢和瑞奇大爷作对的人绝对不会有好下场！}

#{116}{}{Oh just about ten thousand Hub Bucks. Hope you weren't thinking of stealing it. I'd have to kill
# you. I almost killed someone once, so you don't want to mess with me!}
{116}{}{哦，一万个哈勃币。你妄想动这笔钱。我会杀了你的。上次已经把某个不知好歹的打了个半死，你别想！}

#{117}{}{Man, you're stupid. Oh, sorry, I didn't mean to offend you. Now let's try this again. "Yes" means I
# blow your head off. "No" means you get your butt out of here. Which is it going to be?}
{117}{}{伙计，你真是够蠢的。哦，对不起，我没有冒犯你的意思。现在我们换个方式说话。“是”的意思是我把你的头轰飞。“不是”的意思是你赶紧离开这里。你选择哪一个？}

#{118}{}{Ah . . . yes . . .}
{118}{}{嗯……是……}

#{119}{}{Uh?no厎
{119}{}{嗯？喏咯？}

#{120}{}{Runk! Runk!}
{120}{}{喏咯！喏咯！}

#{121}{}{Man, I can't do it! It'd be like shooting a dumb animal. Just get outta here, okay?}
{121}{}{伙计，我不能那么做！我应该打死你这个没脑子的动物。现在快从这里离开，行吗？}

#{122}{}{That's good. Now run along now. I'm sure you might find someone to feed you厎
{122}{}{很好。快跑。我会找人来修理你的！}

#{123}{}{Maybe one runk means "yes" and two runks mean "no". Okay, "runk" means I kill you. "Runk, runk" means
# you leave. Okay?}
{123}{}{也许一个喏咯的意思是“是的”而两个喏咯的意思是“不是”。好。“喏咯”的意思是我杀了你。“喏咯，喏咯”的意思是你走开。怎么样？}

#{124}{}{Runk}
{124}{}{喏咯}

#{125}{}{Runk, runk.}
{125}{}{喏咯，喏咯。}

#{126}{}{Runk, runk, runk!}
{126}{}{喏咯，喏咯，喏咯！}

#{127}{}{Three runks. Shit, this isn't working. Maybe I'll just ignore you and you'll wander off厎
{127}{}{三个“喏咯”。狗屎，不能这样下去了。也许我应该根本不理你，由你自生自灭。}