# {100}{}{You see a citizen of Vault 13.}
# {101}{}{What is the outside world like?}
# {102}{}{You must be brave to venture outside the Vault.}
# {103}{}{The Overseer says that the outside world is dangerous.}
# {104}{}{Be careful while traveling outside the Vault.}
# {105}{}{Don't forget to see the medic if you are hurt.}
# {106}{}{The Overseer makes sure everyone is well cared for in the Vault.}
{100}{}{你看到一个１３号避难所居民。}
{101}{}{外面世界里的人是什么样的？}
{102}{}{你一定要勇敢的到避难所外去冒险。}
{103}{}{监督者说外面的世界很危险。}
{104}{}{在避难所外冒险时要小心啊。}
{105}{}{如果你受伤了不要忘记找个医生。}
{106}{}{监督者负责照顾好避难所里的每一个人。}

