# {100}{}{There is a grenade rigged underneath this floor panel.}
# {101}{}{ It is not armed.}
# {102}{}{You disarm the trap and remove the plasma grenade.}
# {103}{}{You are removing the tripwire from the arming switch when you drop the pin and set off the grenade!}
# {104}{}{You try to slide the panel up slightly and remove the trap, but you are having trouble getting it up without pulling the tripwire.}
# {105}{}{You pry up the plate but you can't get a good grip on the grenade.}
# {106}{}{You pull the plate up, but the tripwire slips from your fingers before you manage to remove it.}
{100}{}{在这地板下面有一个引爆器。}
{101}{}{它没有装上。}
{102}{}{你解除了陷阱并拿掉了电浆手榴弹。}
{103}{}{在即将把手榴弹拆除时，你不慎引爆了它。}
{104}{}{你本打算把地板稍稍抬起来以解除陷阱，但那样的话又免不了会碰到触发引线。}
{105}{}{你在地板缝里仔细查看，但是你无法拿到手榴弹。}
{106}{}{你掀起了地板，但是手榴弹拉环从你手里滑了下去。}