#{100}{}{This is the disk of Vree's autopsy report.}
#{101}{}{Pip Boy displays: File Found on System. Aborting download.}
#{102}{}{Pip Boy displays: Downloading data from Disk.}
{100}{}{这是关于弗蕾尸体解剖报告的磁盘。}
{101}{}{哗哗小子提示：系统错误。下载中断。}
{102}{}{哗哗小子提示：正在从磁盘下载。}